Repository linz/step-ag-grid, pull requests merged in 2022-12, with the labels that each got.

#140 fix: render cells are blank on popover, cancel deferred on unload, catch exceptions in updatingcells, fix single select highligh
  src/components/GridCell.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/styles/GridTheme.scss
  src/utils/deferredPromise.ts
Labels: Extra Small

#141 feat: number validation in text inputs
  config/jest/babelTransform.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/jest/setup.js
  jest.config.js
  package-lock.json
  package.json
  src/utils/textValidator.test.ts
  src/utils/textValidator.ts
  src/utils/util.ts
  tsconfig.json
Labels: Medium

#142 feat: add scale to validator
  src/utils/textValidator.test.ts
  src/utils/textValidator.ts
Labels: Extra Small

#143 fix: Fix bearing correction
  README.md
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/utils/bearing.ts
Labels: Extra Small

#144 feat: hide editable icon on not focused or hovered, feat: shortcut keys for cells
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/gridRender/GridRenderGenericCell.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/styles/Grid.scss
Labels: Extra Small

#145 fix: Fixed bearing correction formatter when type string
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/utils/bearing.ts
Labels: Extra Small

#146 feat: enable single row selection
  src/components/Grid.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Small

#147 fix: single row selection on custom edit
  src/components/Grid.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Small

#148 fix: Use original Bearing correction format
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/utils/bearing.ts
Labels: Extra Small

#149 feat: auto select first row, and wait for external row selection in sync
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Small

#150 docs: Added info to README.md about using testing calls from step-ag-grid
  README.md
Labels: Extra Small

#151 fix: test row selection
  src/components/Grid.tsx
  src/utils/testUtil.ts
Labels: Extra Small

#152 fix: remove selectRow call from editCell
  src/utils/testUtil.ts
Labels: Extra Small

#154 fix: multi line cell edit position
  src/styles/GridTheme.scss
Labels: Extra Small

#155 fix: change hover colour to hint
  src/styles/GridTheme.scss
Labels: Extra Small

#156 fix: bearing regex validation message does not refer to positive numbers
  src/utils/bearing.ts
Labels: Extra Small

#157 fix: readme change to trigger build
  src/react-menu3/README.md
Labels: No Changes

#158 fix: header select keyboard events, and fix select first new cell
  src/components/Grid.tsx
  src/components/gridHeader/GridHeaderSelect.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
Labels: Extra Small

#159 fix: dont focus cell if currently editing
  src/components/Grid.tsx
  src/components/gridHeader/GridHeaderSelect.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#160 fix: tab from filter should save dropdown, unneeded external selected items updates
  src/components/gridForm/GridFormDropDown.tsx
  src/contexts/GridContextProvider.tsx
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Large

#161 fix: disableenterautosave
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Small

#162 fix: async filtered values are empty because of filter
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#163 fix: no options on async options
  src/components/gridForm/GridFormDropDown.tsx
Labels: No Changes

#164 fix: auto focus first cell on auto select first row
  src/components/Grid.tsx
Labels: Extra Small

#165 feat: expose Grid interface to notify client when a column has been m…
  src/components/Grid.tsx
Labels: Extra Small

#166 Dynamic cell editors
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridCellMultiEditor.tsx
  src/components/GridCellMultiSelectClassRules.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/styles/GridTheme.scss
Labels: Medium, released

#168 Feat: Convert to ESM Module
  .eslintrc.cjs
  .prettierrc.cjs
  .storybook/main.cjs
  config/jest/babelTransform.cjs
  config/jest/cssTransform.cjs
  config/jest/fileTransform.cjs
  jest.config.cjs
  package.json
Labels: Extra Small

#170 fix: debounce on getoptions, added row typing to editable
  src/components/GridCellMultiEditor.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridRender/GridRenderGenericCell.tsx
  src/index.ts
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
Labels: Small

#171 feat: add types to valueFormatter, valueGetter
  src/components/gridRender/GridRenderGenericCell.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
Labels: Extra Small
