Repository linz/step-ag-grid, pull requests merged in 2022-11, with the labels that each got.

#54 fix: bearing validation not working, feat: added don't shrink if menu direction is top option
  index.ts
  src/components/GridCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/react-menu3/components/MenuList.tsx
  src/react-menu3/types.ts
  src/stories/components/GridPopoutBearing.stories.tsx
  src/utils/bearing.ts
Labels: Small

#52 fix: pass values record back to save callback
  src/components/gridForm/GridFormMultiSelect.tsx
  src/stories/components/GridPopoutEditMultiSelect.stories.tsx
Labels: Small

#55 fix: Add units to textInputFormatter
  index.ts
  src/components/GridCell.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/lui/TextInputFormatted.tsx
  src/stories/components/FormTest.tsx
  src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
Labels: Small

#56 fix: pass data back to validate, fix: defaultColDef not required
  index.ts
  src/components/Grid.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoutMenu.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
Labels: Small

#57 Ability to add headers to drop downs
  src/components/gridForm/GridFormDropDown.tsx
  src/stories/components/GridPopoutEditDropDown.stories.tsx
Labels: Extra Small

#58 fix: remove position initial from popup menu
  src/components/GridPopoverHook.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#59 BREAKING CHANGE: refactor code to be type safe, renamed updating conext to grid updating context
  index.ts
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridLoadableCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMessage.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoutMenu.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/components/gridPopoverEdit/GridPopoverMessage.ts
  src/components/gridPopoverEdit/GridPopoverTextArea.ts
  src/components/gridPopoverEdit/GridPopoverTextInput.ts
  src/components/gridRender/GridRenderGenericCell.tsx
  src/components/gridRender/GridRenderPopoutMenuCell.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridPopoverContext.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/contexts/GridUpdatingContext.tsx
  src/contexts/GridUpdatingContextProvider.tsx
  src/stories/components/FormTest.tsx
  src/stories/components/GridPopoutBearing.stories.tsx
  src/stories/components/GridPopoutEditDropDown.stories.tsx
  src/stories/components/GridPopoutEditGeneric.stories.tsx
  src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/components/GridPopoutEditMultiSelect.stories.tsx
  src/stories/components/GridReadOnly.stories.tsx
Labels: Extra Large

#60 BREAKING CHANGE: deploy to npm
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#62 fix: Move contexts to own files, use Lui workflows, make mouse down trigger save
  .github/dependabot.yml
  .github/workflows/chromatic.yml
  .github/workflows/deploy-storybook.yml
  README.md
  package.json
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/components/FocusableItem.tsx
  src/react-menu3/components/MenuGroup.tsx
  src/react-menu3/components/MenuItem.tsx
  src/react-menu3/components/MenuList.tsx
  src/react-menu3/components/MenuRadioGroup.tsx
  src/react-menu3/components/SubMenu.tsx
  src/react-menu3/contexts/EventHandlersContext.ts
  src/react-menu3/contexts/HoverItemContext.ts
  src/react-menu3/contexts/ItemSettingsContext.ts
  src/react-menu3/contexts/MenuListContext.ts
  src/react-menu3/contexts/MenuListItemContext.ts
  src/react-menu3/contexts/RadioGroupContext.ts
  src/react-menu3/contexts/SettingsContext.ts
  src/react-menu3/hooks/useItemState.ts
  src/react-menu3/utils/constants.ts
  src/react-menu3/utils/withHovering.tsx
Labels: Large

#68 fix: move index.ts into src, fix use urls to be relative, update package versions
  index.ts
  package-lock.json
  package.json
  packageNotes.txt
  rollup.config.cjs
  src/components/gridPopoverEdit/GridPopoverMenu.scss
  src/index.ts
  src/styles/Grid.scss
  src/styles/GridRenderGenericCell.scss
  src/styles/react-menu-customisations.scss
  tsconfig.json
Labels: Medium

#69 feat: add npm keywords, add story controls for selectable
  package.json
  src/components/Grid.tsx
  src/stories/components/GridPopoutBearing.stories.tsx
  src/stories/components/GridPopoutEditDropDown.stories.tsx
  src/stories/components/GridPopoutEditGeneric.stories.tsx
  src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/components/GridPopoutEditMultiSelect.stories.tsx
  src/stories/components/GridReadOnly.stories.tsx
Labels: Extra Small

#70 fix: readme code example
  README.md
  src/stories/components/GridPopoutEditDropDown.stories.tsx
Labels: Extra Small

#71 fix: storybook url no longer private
  README.md
Labels: Extra Small

#72 fix: index.d.ts types issues, fix: semantic release package versioning, fix: postSortRows
  package.json
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/PostSortRowsHook.ts
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMessage.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoutMenu.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/components/gridPopoverEdit/GridPopoverMessage.ts
  src/components/gridPopoverEdit/GridPopoverTextArea.ts
  src/components/gridPopoverEdit/GridPopoverTextInput.ts
  src/components/gridRender/GridRenderGenericCell.tsx
  src/components/gridRender/GridRenderPopoutMenuCell.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/index.ts
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/components/FormTest.tsx
  src/stories/components/GridPopoutBearing.stories.tsx
  src/stories/components/GridPopoutEditDropDown.stories.tsx
  src/stories/components/GridPopoutEditGeneric.stories.tsx
  src/stories/components/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/components/GridPopoutEditMultiSelect.stories.tsx
  src/stories/components/GridReadOnly.stories.tsx
  src/stories/components/ReactMenu.stories.tsx
  tsconfig.json
Labels: Large

#73 fix: add missing package conventional-changelog-conventionalcommits
  package-lock.json
  package.json
Labels: Extra Small

#74 fix: temp-remove-semantic-config-until-fix-available
  README.md
  package.json
Labels: Extra Small

#75 feat: Added Action button and demo
  package-lock.json
  package.json
  src/index.ts
  src/lui/ActionButton.scss
  src/lui/ActionButton.tsx
  src/lui/reactUtils.test.tsx
  src/lui/reactUtils.tsx
  src/lui/stateDeferredHook.tsx
  src/lui/timeoutHook.test.tsx
  src/lui/timeoutHook.tsx
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/FormTest.scss
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/GridPopoutEditGeneric.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/react-menu/ReactMenu.stories.tsx
Labels: Large

#76 fix: export missing types from forms, fix: don't close menu if modal dialog is open
  src/components/GridPopoverHook.tsx
  src/index.ts
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/types.ts
Labels: Extra Small

#77 Issue/modal closes editor
  src/components/GridPopoverHook.tsx
  src/stories/grid/FormTest.tsx
Labels: Extra Small

#78 fix: modals no longer closed by onBlur of menu
  src/stories/grid/FormTest.tsx
Labels: Extra Small

#80 feat: add initial values object to multi drop down, implement subcomponents, altered save signature
  src/components/GridSubComponentTextArea.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridForm/GridSubComponentProps.ts
  src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/components/gridPopoverEdit/GridPopoverMessage.ts
  src/components/gridPopoverEdit/GridPopoverTextArea.ts
  src/components/gridPopoverEdit/GridPopoverTextInput.ts
  src/lui/TextInputFormatted.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
Labels: Large

#82 fix: ControlledMenu error
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/grid/FormTest.tsx
Labels: Small

#83 fix: ControlledMenu error
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Small

#84 feat: improved subComponents using a context
  src/components/GridSubComponentTextArea.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridForm/GridSubComponentProps.ts
  src/contexts/GridSubComponentContext.ts
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/GridPopoutEditGeneric.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Medium

#79 feat/dropdown subcomponent
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/index.ts
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
Labels: Extra Large

#91 fix: ignore unexpected console in story
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
Labels: Extra Small

#85 fix: action button manages own state
  package.json
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/lui/ActionButton.tsx
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Small

#92 fix: apply styles to text input
  src/components/gridForm/GridFormSubComponentTextInput.tsx
Labels: Extra Small

#93 fix: post sort rows hook doesnt sort on swap
  package.json
  src/components/PostSortRowsHook.ts
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/lui/ActionButton.tsx
  src/stories/components/ActionButton.stories.tsx
Labels: Medium

#94 fix: justify popout menu to the right
  package-lock.json
  package.json
  packageNotes.txt
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/components/gridPopoverEdit/GridPopoverMessage.ts
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Large

#96 fix: remove todos
  package.json
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/contexts/GridContextProvider.tsx
  src/index.ts
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/components/Menu.tsx
  src/react-menu3/components/MenuButton.tsx
  src/react-menu3/components/MenuGroup.tsx
  src/react-menu3/components/MenuItem.tsx
  src/react-menu3/components/SubMenu.tsx
  src/react-menu3/hooks/useBEM.ts
Labels: Extra Small

#97 fix: allow subcomponent to save on tab
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/styles/GridFormSubComponentTextInput.scss
Labels: Medium

#100 fix: sizeColumnsToFit errors in test
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#101 fix: subcomponet close after save
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
Labels: Medium

#102 fix: pass event to keydown
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
Labels: Extra Small

#103 fix: remove breaking line
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#104 feat: Added props onFocus and onClick to component TextInputFormatted
  src/lui/TextInputFormatted.tsx
Labels: Extra Small

#105 feat: subcomponents-in-popover-menus, focus inputs on mouseover
  src/components/GridSubComponentTextArea.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/lui/TextAreaInput.tsx
  src/lui/TextInputFormatted.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Medium

#106 fix: multi select now wont save if data hasnt changed
  src/components/gridForm/GridFormMultiSelect.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
Labels: Small

#107 fix: react menu window resize observer
  src/react-menu3/components/MenuList.tsx
Labels: Extra Small

#108 BREAKING CHANGE: forms now get values from context
  src/components/GridCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMessage.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridPopoverContext.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/react-menu3/components/MenuList.tsx
  src/react-menu3/contexts/SettingsContext.ts
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Large

#109 fix: generic type the popup context, feat add default action to menu
  .dev.eslintrc.js
  .eslintrc.js
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMessage.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridPopoverContext.tsx
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
Labels: Medium

#110 fix: missing context exports
  src/index.ts
Labels: Extra Small

#111 feat: inputProps removed, fix row selection via keyboard, feat common keyboard handlers
  .prettierrc.js
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/GridSubComponentTextArea.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/index.ts
  src/lui/TextAreaInput.tsx
  src/lui/TextInputFormatted.tsx
  src/react-menu3/components/MenuItem.tsx
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/utils/textValidator.ts
Labels: Extra Large

#112 fix: prevent tab out of div in genericinput and textarea
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
Labels: Extra Small

#113 fix: missing data on custom validate
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridSubComponentContext.ts
  src/utils/textValidator.ts
Labels: Small

#115 BREAKING CHANGE: implement tab to finish edit, replace manual keyboard handler with auto
  package-lock.json
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridPopoverContext.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/contexts/GridUpdatingContext.tsx
  src/contexts/GridUpdatingContextProvider.tsx
  src/lui/FormError.tsx
  src/lui/TextAreaInput.tsx
  src/lui/TextInputFormatted.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/components/MenuItem.tsx
  src/react-menu3/types.ts
  src/react-menu3/utils/constants.ts
  src/stories/grid/FormTest.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/styles/GridFormDropDown.scss
Labels: Extra Large

#116 fix: tab on multi selects
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Small

#119 BREAKING CHANGE: validate now invalid, removed valueType generic off popoverEditDropdown
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridPopoverContextProvider.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/utils/bearing.ts
  src/utils/textValidator.ts
Labels: Large

#120 feat: added disableEnterAutoSave flag
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/grid/FormTest.tsx
Labels: Extra Small

#121 fix: subcomponent change detection in dropdowns
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#122 BREAKING CHANGE: multiselect headers, filters
  package-lock.json
  package.json
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridPopoverEdit/GridPopoutEditMultiSelect.ts
  src/contexts/GridSubComponentContext.ts
  src/lui/ActionButton.tsx
  src/lui/FormError.scss
  src/lui/FormError.tsx
  src/lui/TextAreaInput.tsx
  src/lui/TextInputFormatted.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/components/MenuList.tsx
  src/react-menu3/hooks/useItems.ts
  src/react-menu3/utils/utils.ts
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/styles/Grid.scss
  src/styles/lui-overrides.scss
  src/utils/textMatcher.ts
  src/utils/textValidator.ts
  src/utils/util.ts
Labels: Extra Large

#123 fix: Action button sizing
  src/lui/ActionButton.scss
  src/lui/ActionButton.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/FormTest.tsx
Labels: Extra Small

#124 fix: suppress unwanted grid keyboard events, [Empty] is now _No options_ in dropdown
  src/components/GridCell.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/styles/GridFormDropDown.scss
Labels: Extra Small

#125 fix: filter text selection not working in dropdown
  src/components/gridForm/GridFormDropDown.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
Labels: Small

#126 Fix filter text selection not working in dropdown
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#128 feat: add support for tests
  rollup.config.cjs
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/index.ts
  src/react-menu3/components/ControlledMenu.tsx
  src/utils/testQuick.ts
  src/utils/testUtil.ts
Labels: Large

#129 fix: not filtering in multiselect popover
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/utils/textMatcher.ts
Labels: Medium

#130 feat: add missing grid options row class, animate rows, defaultColDef
  .github/workflows/deploy-storybook.yml
  src/components/GenericCellClass.tsx
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridCellMultiSelectClassRules.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/index.ts
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
Labels: Extra Small

#131 feat: add cellContains for testing
  .gitattributes
  src/components/gridForm/GridFormDropDown.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/utils/testQuick.ts
  src/utils/testUtil.ts
Labels: Small

#132 fix: testutils-not-finding-menu-options-and-subcomponents
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/utils/testUtil.ts
Labels: Extra Small

#133 fix: tests not waiting long enough
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/utils/testUtil.ts
Labels: Extra Small

#134 feat: rename cellContains to findCellContains, add countrows
  src/utils/testUtil.ts
Labels: Extra Small

#135 feat: ActionButton onAction renamed to onClick, added findParentByClassName
  src/lui/ActionButton.tsx
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/utils/util.ts
Labels: Extra Small

#136 fix: reverting previous commit that caused dropdown component labels …
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#137 fix: datatestids sometimes not showing, action button icon rotation and sizing
  package-lock.json
  package.json
  src/components/Grid.tsx
  src/lui/ActionButton.scss
  src/lui/ActionButton.tsx
  src/stories/components/ActionButton.stories.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
Labels: Small
