Repository linz/step-ag-grid, pull requests merged in 2023-06, with the labels that each got.

#314 SURVEY-16594 UI enter and tab changes
  package-lock.json
  package.json
  packageNotes.txt
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/utils/utils.ts
  src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
Labels: Medium

#315 SURVEY-16594 UI enter and tab changes _ fix lint errors
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Small

#317 Fix excessively grid size callbacks and grid size now ignores hidden columns
  src/components/Grid.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#319 Tab whilst editing edits next available field
  README.md
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridUpdatingContext.tsx
  src/contexts/GridUpdatingContextProvider.tsx
  src/react-menu3/components/MenuList.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoverEditDropDown.stories.tsx
  src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
Labels: Large

#320 Pinned columns, deferred resize
  src/components/Grid.tsx
  src/contexts/GridContextProvider.tsx
  src/lui/timeoutHook.tsx
Labels: Small

#321 default select pinned column to null
  src/components/Grid.tsx
Labels: Extra Small

#322 Fix tab from start or end of grid incorrectly edits
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#324 Fix updating dependant column autosize
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/contexts/GridUpdatingContext.tsx
  src/contexts/GridUpdatingContextProvider.tsx
Labels: Small

#325 SURVEY-17202 adding the ability to place a cell in editing mode
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#329 Feature/SURVEY-17202 add ability to switch off column sorting for a whole table.
  src/components/Grid.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#330 fix/SURVEY-17202 revert Grid.startCelLEditing back to it's original
  src/components/Grid.tsx
Labels: Extra Small

#331 feat: SURVEY-17487 Optional show zero seconds
  src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
  src/utils/bearing.test.ts
  src/utils/bearing.ts
Labels: Small

#333 Add not zero validation to numbers
  src/utils/textValidator.test.ts
  src/utils/textValidator.ts
  src/utils/util.test.ts
  src/utils/util.ts
Labels: Extra Small

#335 fix(step-ag-grid): SURVEY-16691: Ensure grid cells get initial size at start
  src/components/Grid.tsx
Labels: bug, Extra Small

#336 Multi select grid
  README.md
  package-lock.json
  package.json
  src/components/Grid.tsx
  src/components/gridForm/GridFormMultiSelectGrid.tsx
  src/components/gridForm/index.ts
  src/components/gridPopoverEdit/GridPopoutEditMultiSelectGrid.ts
  src/components/gridPopoverEdit/index.ts
  src/react-menu3/components/MenuList.tsx
  src/react-menu3/contexts/HoverItemContext.ts
  src/react-menu3/hooks/useItems.ts
  src/react-menu3/utils/withHovering.tsx
  src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
  src/stories/react-menu/ReactMenu.stories.tsx
  src/styles/GridFormMultiSelectGrid.scss
  src/styles/index.scss
  tsconfig.json
Labels: Large

#337 Support JSX in multiselect grid
  src/components/Grid.tsx
  src/components/gridForm/GridFormMultiSelectGrid.tsx
  src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
Labels: Extra Small
