Repository linz/step-ag-grid, pull requests merged in 2023-01, with the labels that each got.

#173 feat: added test function for cell editor input
  src/utils/testUtil.ts
Labels: Extra Small

#174 feat: added test function for validating menu options
  src/utils/testUtil.ts
Labels: Extra Small

#175 Feat added type input test util functions
  src/utils/testUtil.ts
Labels: Extra Small

#177 fix: wrapping test input userevents in act
  src/utils/testUtil.ts
Labels: Extra Small

#178 fix: adding wait to typeInput calls
  src/utils/testUtil.ts
Labels: Extra Small

#172 fix: default column prop not being used
  src/components/Grid.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
Labels: Medium

#179 fix: openAndClickMenuOption was not always firing the click event
  src/utils/testUtil.ts
Labels: Extra Small

#180 fix: added textarea to type input util functions
  src/utils/testUtil.ts
Labels: Extra Small

#181 feat: added reaonly cell check function
  src/utils/testUtil.ts
Labels: Extra Small

#182 fix: fixing readonly check test util function
  src/utils/testUtil.ts
Labels: Extra Small

#169 Feat: Add new prop alwaysShowVerticalScroll
  src/components/Grid.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
Labels: Extra Small

#183 feat: added openAndFindMenuOption test util function
  src/utils/testUtil.ts
Labels: Extra Small

#184 feat: export find popover and make containers optional
  src/utils/testUtil.ts
Labels: Extra Small

#185 fix: minwidth on action menu
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
Labels: Extra Small

#187 fix: test util fixes to clear console errors
  src/utils/testUtil.ts
Labels: Extra Small

#189 fix: added group key to multiselect
  src/components/gridForm/GridFormMultiSelect.tsx
Labels: Extra Small

#190 fix: adding act wrapper to findRow
  src/utils/testUtil.ts
Labels: Extra Small

#191 fix: text input width not applied correctly
  src/components/gridForm/GridFormTextInput.tsx
Labels: Extra Small

#192 BREAKING CHANGE: use named params instead of positional
  src/components/Grid.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/react-menu3/components/ControlledMenu.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoutEditMultiSelect.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/grid/gridForm/GridFormDropDown.stories.tsx
  src/stories/grid/gridForm/GridFormEditBearing.stories.tsx
  src/stories/grid/gridForm/GridFormEditBearingCorrection.stories.tsx
  src/stories/grid/gridForm/reactMenuTest.scss
  src/utils/bearing.ts
Labels: Large

#194 fix: GridFormTests
  src/components/GridCell.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormEditBearing.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridPopoverEdit/GridPopoverEditBearing.ts
  src/components/gridPopoverEdit/GridPopoverEditDropDown.ts
  src/react-menu3/styles/_var.scss
  src/stories/grid/gridForm/GridFormDropDown.stories.tsx
  src/stories/grid/gridForm/GridFormEditBearing.stories.tsx
  src/stories/grid/gridForm/GridFormEditBearingCorrection.stories.tsx
  src/stories/grid/gridForm/GridFormMessage.stories.tsx
  src/stories/grid/gridForm/GridFormMultiSelect.stories.tsx
  src/stories/grid/gridForm/GridFormTextArea.stories.tsx
  src/stories/grid/gridForm/GridFormTextInput.stories.tsx
  src/styles/Grid.scss
  src/styles/GridFormMultiSelect.scss
  src/styles/GridIcon.scss
  src/styles/lui-overrides.scss
  src/styles/react-menu-customisations.scss
  src/utils/bearing.test.ts
  src/utils/bearing.ts
Labels: Large

#195 fix: popup menu not closing on action after invalid subcomponent, cell edit stop steals focus
  src/components/Grid.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/grid/gridForm/GridFormMultiSelect.stories.tsx
Labels: Extra Small

#196 fix focus lost on dialogs
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#197 fix: editable inheritance, dropdown incorrectly selecting on click away
  src/components/Grid.tsx
  src/components/GridCell.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
Labels: Small

#199 fix: grid readonly flag is inverted
  src/components/Grid.tsx
  src/stories/grid/GridPopoutBearing.stories.tsx
Labels: Extra Small

#200 fix: dropdown should not save on blur
  src/components/GridPopoverHook.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Small

#201 feat: Create default filter value getter if there's a value formatter
  src/components/GridCell.tsx
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridRender/GridRenderGenericCell.tsx
Labels: Extra Small

#202 Use getter values as well as formatted for filter
  config/jest/setup.js
  package-lock.json
  package.json
  src/components/GridCell.test.tsx
  src/components/GridCell.tsx
  src/components/gridRender/GridRenderGenericCell.tsx
  src/setupTests.ts
  src/stories/grid/GridPopoutBearing.stories.tsx
Labels: Small
