Repository linz/step-ag-grid, pull requests merged in 2023-02, with the labels that each got.

#203 fix wrong relative path to context
  .npmrc
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
Labels: Extra Small

#204 Grid interaction tests
  src/components/gridForm/GridFormDropDown.tsx
  src/components/gridForm/GridFormMultiSelect.tsx
  src/components/gridForm/GridFormPopoverMenu.tsx
  src/components/gridForm/GridFormSubComponentTextArea.tsx
  src/components/gridForm/GridFormSubComponentTextInput.tsx
  src/components/gridForm/GridFormTextArea.tsx
  src/components/gridForm/GridFormTextInput.tsx
  src/lui/TextAreaInput.tsx
  src/lui/TextInputFormatted.tsx
  src/react-menu3/components/MenuItem.tsx
  src/react-menu3/utils/withHovering.tsx
  src/stories/grid/GridPopoutEditDropDown.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormDropDownInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormEditBearingInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormPopoverMenuInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormTextAreaInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormTextInputInteraction.stories.tsx
  src/stories/grid/gridFormStatic/GridFormDropDown.stories.tsx
  src/stories/grid/gridFormStatic/GridFormEditBearing.stories.tsx
  src/stories/grid/gridFormStatic/GridFormEditBearingCorrection.stories.tsx
  src/stories/grid/gridFormStatic/GridFormMessage.stories.tsx
  src/stories/grid/gridFormStatic/GridFormMultiSelect.stories.tsx
  src/stories/grid/gridFormStatic/GridFormPopoverMenu.stories.tsx
  src/stories/grid/gridFormStatic/GridFormTextArea.stories.tsx
  src/stories/grid/gridFormStatic/GridFormTextInput.stories.tsx
Labels: Extra Large

#206 webpack 5 release
  .storybook/main.cjs
  package-lock.json
  package.json
  src/components/gridForm/GridFormMultiSelect.tsx
Labels: Extra Small

#207 BREAKING CHANGE: Move aggrid peerdeps to deps
  package-lock.json
  package.json
  src/components/GridCell.tsx
  src/react-menu3/hooks/useMenuState.ts
Labels: Extra Small

#208 fix: make aggrid 28 header same as 27
  src/styles/Grid.scss
Labels: Extra Small

#215 BREAKING CHANGE: Revert to v27 aggrid
  package-lock.json
  package.json
  src/components/Grid.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/styles/Grid.scss
  src/utils/textValidator.test.ts
  src/utils/textValidator.ts
Labels: Extra Small

#216 multi select test flakyness, text enter to save filter
  src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
Labels: Extra Small

#219 dont show row selection header when row selection is set to single
  src/components/Grid.tsx
Labels: Extra Small

#220 External grid filters
  src/components/Grid.tsx
  src/components/GridFilter.ts
  src/components/GridWrapper.tsx
  src/components/gridFilter/GridFilterQuick.tsx
  src/components/gridFilter/GridFilters.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridPopoverEditBearing.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/styles/Grid.scss
Labels: Large

#222 BREAKING CHANGE: release filters
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Small

#223 fix: Expose grid filters to allow use in external projects
  src/index.ts
Labels: Extra Small

#228 GridFilterButtons
  src/components/GridFilter.ts
  src/components/gridFilter/GridFilterButtons.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Small

#230 Fix lint issue double import
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Extra Small
