Repository linz/step-ag-grid, pull requests merged in 2023-08, with the labels that each got.

#357 fix: SURVEY-15720 support user event v14
  src/utils/testQuick.ts
  src/utils/testUtil.ts
Labels: Small

#359 fix: SURVEY-15720 Change to use customised user event
  src/utils/testUtil.ts
Labels: Extra Small

#361 Make findquick log text matchers on failures
  src/utils/testQuick.ts
Labels: Extra Small

#362 Fix react 18 default focus, upgrade storybook
  .eslintrc.cjs
  .github/workflows/chromatic.yml
  .prettierrc.cjs
  .storybook/main.cjs
  package-lock.json
  package.json
  src/components/Grid.tsx
  src/components/GridIcon.tsx
  src/components/GridNoRowsOverlay.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/lui/reactUtils.test.tsx
  src/stories/grid/GridFilterButtons.stories.tsx
  src/stories/grid/GridNoRowsOverlay.stories.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormDropDownInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormEditBearingCorrectionInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormEditBearingInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormMultiSelectGridInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormPopoverMenuInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormTextAreaInteraction.stories.tsx
  src/stories/grid/gridFormInteraction/GridFormTextInputInteraction.stories.tsx
  src/stories/grid/gridFormStatic/GridFormDropDown.stories.tsx
  src/stories/grid/gridFormStatic/GridFormEditBearing.stories.tsx
  src/stories/grid/gridFormStatic/GridFormEditBearingCorrection.stories.tsx
  src/stories/grid/gridFormStatic/GridFormMessage.stories.tsx
  src/stories/grid/gridFormStatic/GridFormMultiSelect.stories.tsx
  src/stories/grid/gridFormStatic/GridFormPopoverMenu.stories.tsx
  src/stories/grid/gridFormStatic/GridFormTextArea.stories.tsx
  src/stories/grid/gridFormStatic/GridFormTextInput.stories.tsx
  src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
  src/stories/react-menu/ReactMenu.stories.tsx
Labels: Extra Large

#365 Update actions to node 18
  .eslintrc.cjs
  .github/workflows/deploy-storybook.yml
  package-lock.json
  package.json
  src/stories/grid/GridFilterButtons.stories.tsx
  src/stories/grid/GridNoRowsOverlay.stories.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
  src/stories/grid/GridPopoutContextMenu.stories.tsx
  src/stories/grid/GridPopoutEditGeneric.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoverEditBearing.stories.tsx
  src/stories/grid/GridPopoverEditDropDown.stories.tsx
  src/stories/grid/GridPopoverEditMultiSelect.stories.tsx
  src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
  src/styles/GridTheme.scss
Labels: Small

#366 Deploy
  .prettierrc.cjs
Labels: Extra Small

#368 Ignore redrawRows exceptions
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#375 Fix selection cell styles, debounce redraw rows, add waitForGridReady
  README.md
  src/components/Grid.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridFilterButtons.stories.tsx
  src/stories/grid/GridNonEditableRow.stories.tsx
  src/stories/grid/GridPopoutContextMenu.stories.tsx
  src/stories/grid/GridPopoutEditGeneric.stories.tsx
  src/stories/grid/GridPopoutEditGenericTextArea.stories.tsx
  src/stories/grid/GridPopoverEditBearing.stories.tsx
  src/stories/grid/GridPopoverEditDropDown.stories.tsx
  src/stories/grid/GridPopoverEditMultiSelect.stories.tsx
  src/stories/grid/GridPopoverEditMultiSelectGrid.stories.tsx
  src/stories/grid/GridReadOnly.stories.tsx
  src/stories/grid/interactions/GridKeyboardInteractions.stories.tsx
  src/styles/GridTheme.scss
  src/utils/storybookTestUtil.ts
Labels: Medium

#377 Dont sort popovers and some test utils
  src/components/gridPopoverEdit/GridPopoverMenu.tsx
  src/contexts/GridContextProvider.tsx
  src/utils/storybookTestUtil.ts
  src/utils/testUtil.ts
Labels: Extra Small

#378 Make waitForGrid props optional
  src/utils/testUtil.ts
Labels: Extra Small

#379 wait for grid row Timeout is optional
  src/utils/testUtil.ts
Labels: Extra Small

#381 Fix autosizing flex columns
  src/components/Grid.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#382 Set default grid height to match grid scss
  src/components/Grid.tsx
Labels: Extra Small

#369 feat: Survey 10146 input auto focus
  src/components/gridForm/GridFormMultiSelect.tsx
  src/stories/grid/gridFormInteraction/GridFormMultiSelectInteraction.stories.tsx
Labels: Extra Small

#385 Remove closeMenuExclusionClassName
  src/components/GridPopoverHook.tsx
  src/react-menu3/components/ControlledMenu.tsx
  src/react-menu3/types.ts
Labels: Extra Small

#386 chore: fix ag-grid as v29
  package-lock.json
  package.json
Labels: Extra Small

#387 feat: Ag grid community v29
  README.md
Labels: Extra Small

#383 feat: enabled drag/drop moving rows
  src/components/Grid.tsx
  src/stories/grid/GridDragRow.stories.tsx
  src/styles/Grid.scss
  src/styles/GridTheme.scss
Labels: Medium

#389 Fix modal dialog issues
  src/react-menu3/components/ControlledMenu.tsx
Labels: Extra Small

#391 fix: select column checkbox now centered correctly in row and header
  src/styles/GridTheme.scss
Labels: Extra Small

#392 fix: row drag moving row prematurely
  src/components/Grid.tsx
  src/stories/grid/GridDragRow.stories.tsx
Labels: Extra Small

#396 Dont allow save whilst options are loading GridFormDropdown
  src/components/gridForm/GridFormDropDown.tsx
Labels: Extra Small

#399 fix: row drag issues
  src/components/Grid.tsx
Labels: Extra Small

#339 test: SURVEY-17302 Update test utilities so that they support pinned
  src/utils/testUtil.ts
Labels: Extra Small

#406 Move css into GridTheme
  src/stories/grid/GridDragRow.stories.tsx
  src/styles/Grid.scss
  src/styles/GridTheme.scss
Labels: Medium

#407 Fix multi themes 2
  src/components/Grid.tsx
  src/styles/GridTheme.scss
Labels: Extra Small

#408 fix: findRow was erroring if no pinned columns present
  src/utils/testUtil.ts
Labels: Extra Small

#410 Fix overridden lui styles
  package-lock.json
  package.json
  src/lui/FormError.scss
  src/lui/FormError.tsx
  src/lui/TextInputFormatted.scss
  src/lui/TextInputFormatted.tsx
  src/stories/grid/FormTest.scss
Labels: Extra Small
