Repository linz/step-ag-grid, pull requests merged in 2023-07, with the labels that each got.

#343 fix: SURVEY-18028 clear selections after adding a new row
  src/contexts/GridContextProvider.tsx
Labels: Extra Small

#346 Fix broken use effect missing deps
  README.md
  src/components/Grid.tsx
  src/lui/timeoutHook.tsx
Labels: Extra Small

#347 Remove sanitize filename due to use of buffer
  package-lock.json
  package.json
  src/utils/util.test.ts
  src/utils/util.ts
Labels: Extra Small

#348 Fixes for group columns
  src/components/Grid.tsx
  src/components/gridFilter/GridFilterColumnsToggle.tsx
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Small

#349 Add filler column
  README.md
  src/components/GridCellFiller.tsx
  src/components/gridFilter/GridFilterColumnsToggle.tsx
  src/components/gridUtil.ts
  src/components/index.ts
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridReadOnly.stories.tsx
Labels: Medium

#352 BREAKING CHANGE: correctly export common js.
  package.json
Labels: automerge 🚀, Extra Small

#354 fix: SURVEY-15720 Infer the return type, new RTL returns a promise fo…
  src/utils/testUtil.ts
Labels: Extra Small

#355 fix: SYRVEY-15720 Add missing awaits
  package-lock.json
  package.json
  src/utils/testUtil.ts
Labels: Extra Small

#341 Context menus
  README.md
  src/components/Grid.tsx
  src/components/gridHook/index.ts
  src/components/gridHook/useGridContextMenu.tsx
  src/components/index.ts
  src/contexts/GridContext.tsx
  src/contexts/GridContextProvider.tsx
  src/stories/grid/GridPopoutContextMenu.stories.tsx
Labels: Large
